### ISSUE TITLE
F1 Button not working

### ISSUE THREAD

**Issue by SlappMann** [BepInEx/BepInEx.ConfigurationManager#13]
when I press the f1 button it does not open the config manager, I followed the instructions to put the config manager dll into the plugins file but it does not work

**Comment by ManlyMarco** [comment]
Make sure bepinex starts up correctly and check game log or bepinex console for loading errors. It's best to turn on the bepinex console either way to see if things work correctly.

**Comment by Roofster** [comment]
F1 brings the config manager up, but does not turn it off.

**Comment by ManlyMarco** [comment]
> F1 brings the config manager up, but does not turn it off.

Click anywhere outside of the window to close it. Input fields capture keyboard input so it can't be used to close the window.

**Comment by Roofster** [comment]
So, that will save the settings to the config file while the game is running.

**Comment by ManlyMarco** [comment]
Settings are changed immediately as you interact with the interface.
