### ISSUE TITLE
can't see mouse cursor

### ISSUE THREAD

**Issue by Boatsandlogs** [BepInEx/BepInEx.ConfigurationManager#16]
I can't see my mouse cursor when I press F1 to bring up the configuration in game, it makes it very difficult to click on things.  is windowed mode an issue?

**Comment by ManlyMarco** [comment]
It depends on the game, some games might require special handling of the cursor (e.g. patching relevant game code). Your best bet is to open config manager while inside of a game menu that shows the cursor. If that doesn't help then you'll likely need a solution specific for your game (usually a helper plugin like [this](https://github.com/IllusionMods/BepisPlugins/blob/master/src/KK_ConfigurationManager/KK.ConfigurationManager.cs)).

**Comment by httpsColon** [comment]
hearthstone , right?
