### ISSUE TITLE
Changing the default Keybinding.

### ISSUE THREAD

**Issue by RainyJimbo** [BepInEx/BepInEx.ConfigurationManager#17]
Where can we change the keybind to? I tried looking at the BepInEx.cfg file that I have for Valheim but it does not seem to have an option there and is conflicting with a keybind for other mods.

**Comment by Windows10CE** [comment]
BepInEx/config/com.bepis.bepinex.configurationmanager.cfg

**Comment by RainyJimbo** [comment]
Thank you very much for the quick response
