### ISSUE TITLE
Request to add ConfigurationManager to Thunderstore

### ISSUE THREAD

**Issue by GreyHak** [BepInEx/BepInEx.ConfigurationManager#19]
Could you please add ConfigurationManager to https://dsp.thunderstore.io/?  I'm a mod developer, and would like your great interface to be available to users.  I can't add the ConfigurationManager dependency unless the library is available.  Thank you.

**Comment by ManlyMarco** [comment]
You shouldn't need to add ConfigurationManager as a plugin dependency in most cases, it's only done when adding custom UI for a specific game (check the developers part of the readme). Why do you need it to be added to thunderstore?

**Comment by GreyHak** [comment]
@ManlyMarco It is my understanding that I need to add ConfigurationManager as a plugin dependency if (a) I need to get an event when ConfigurationManager changes my configuration, or (b) I need to specify a range of acceptable values.  Can these be done without a dependency?

**Comment by Windows10CE** [comment]
a. https://bepinex.github.io/bepinex_docs/master/api/BepInEx.Configuration.ConfigEntry-1.html#BepInEx_Configuration_ConfigEntry_1_SettingChanged
b. https://bepinex.github.io/bepinex_docs/master/api/BepInEx.Configuration.html#acceptablevaluerange-t

**Comment by GreyHak** [comment]
@Windows10CE Thank you for teaching me again.
