### ISSUE TITLE
Config menu only shows a gray box.

### ISSUE THREAD

**Issue by turtlelover73** [BepInEx/BepInEx.ConfigurationManager#25]
Using BepInEx 5.4.9 on Outward, and when I open the config manager, it just shows a blank gray box with no options or anything.

**Comment by ManlyMarco** [comment]
Post the output log.

**Comment by turtlelover73** [comment]
Here you go.

> [Message:   BepInEx] BepInEx 5.4.9.0 - Outward
> [Info   :   BepInEx] Running under Unity v2018.4.8.10209753
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 15 plugins to load
[Info   :   BepInEx] Loading [Partiality Wrapper 1.0]
[Info   :   BepInEx] Loading [Configuration Manager 16.1]
[Info   :   BepInEx] Loading [DrinkWhileRunning 1.2]
[Info   :   BepInEx] Loading [SideLoader 3.4.2]
[Message:SideLoader] Version 3.4.2 starting...
[Info   :   BepInEx] Loading [Combat HUD 5.2]
[Message:Combat HUD] Combat HUD started, version 5.2
[Info   :   BepInEx] Loading [Combat Tweaks 3.1]
[Info   :   BepInEx] Loading [Custom Weight 2.3]
[Info   :   BepInEx] Loading [More Map Details 1.5]
[Info   :   BepInEx] Loading [Multiple Quickslot Bars 1.2.0]
[Info   :   BepInEx] Loading [Outward Minimap 1.5.0]
[Info   :   BepInEx] Loading [SharedModConfig 2.0]
[Info   :   BepInEx] Loading [Shared Quest Rewards 3.0]
[Info   :   BepInEx] Loading [MoreGatherableLoot 1.0.5]
[Info   :   BepInEx] Loading [Soroborean DLC Travel Unleashed 1.0.0]
[Info   :   BepInEx] Loading [Meditation 2.0.0.1]
[Info   :Meditation] Awaken
[Message:   BepInEx] Chainloader startup complete
[Message:SideLoader] Set up custom keybinding 'SideLoader Menu', actionID: 138
[Message:SideLoader] Set up custom keybinding 'Next Quickslot Bar', actionID: 139
[Message:SideLoader] Set up custom keybinding 'Previous Quickslot Bar', actionID: 140
[Message:SideLoader] Set up custom keybinding 'Toggle Minimap', actionID: 141
[Message:SideLoader] Set up custom keybinding 'Shared Mod Config Menu', actionID: 142
[Info   :   Console] Searching for compatible XInput library...
[Info   :   Console] Found Xinput1_4.dll.
[Message:SideLoader] Registered SideLoader RPCManager with view ID 899
[Message:SideLoader] Built FX prefab dictionaries
[Message:SideLoader] Found SLPack 'SharedModConfig'
[Message:SideLoader] Found SLPack 'sinai-dev CombatHUD'
[Message:SideLoader] Loaded assetbundle sharedmodconfig
[Message:SideLoader] Loaded assetbundle combathud
[Message:SideLoader] SideLoader Setup Finished
[Message:SideLoader] -------------------------
[Message:SideLoader] SL Setup took 0.4267435 seconds
[Message:Combat HUD] Combat HUD finished setting up
[Message:SideLoader] Finished invoking OnPacksLoaded.
[Message:SideLoader] Loaded UI bundle
[Message:SideLoader] Set SceneResetWanted: False
[Message:SideLoader]` Checking SL_Character spawns (CierzoTutorial)

**Comment by ManlyMarco** [comment]
I meant the actual unity log file. If you don't know where it is then you can open it from config manager window or from runtime editor window by clicking the Log button.

**Comment by GingerBeardMan7** [comment]
Is this helpful at all? Having the same issue.

[Error  : Unity Log] ArgumentException: Getting control 1's position in a group with only 1 controls when doing repaint
Aborting
Stack trace:
UnityEngine.GUILayoutGroup.GetNext () (at <58f888e0d56a4620958c8e58a768c70d>:0)
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at <58f888e0d56a4620958c8e58a768c70d>:0)
UnityEngine.GUILayout.BeginScrollView (UnityEngine.Vector2 scrollPosition, System.Boolean alwaysShowHorizontal, System.Boolean alwaysShowVertical, UnityEngine.GUIStyle horizontalScrollbar, UnityEngine.GUIStyle verticalScrollbar, UnityEngine.GUIStyle background, UnityEngine.GUILayoutOption[] options) (at <58f888e0d56a4620958c8e58a768c70d>:0)
UnityEngine.GUILayout.BeginScrollView (UnityEngine.Vector2 scrollPosition, System.Boolean alwaysShowHorizontal, System.Boolean alwaysShowVertical, UnityEngine.GUILayoutOption[] options) (at <58f888e0d56a4620958c8e58a768c70d>:0)
ConfigurationManager.ConfigurationManager.SettingsWindow (System.Int32 id) (at <1ee2b014d8854595b396c981966ef778>:0)
UnityEngine.GUILayout+LayoutedWindow.DoWindow (System.Int32 windowID) (at <58f888e0d56a4620958c8e58a768c70d>:0)
UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI+WindowFunction func, System.Int32 id, System.Int32 instanceID, UnityEngine.GUISkin _skin, System.Int32 forceRect, System.Single width, System.Single height, UnityEngine.GUIStyle style) (at <58f888e0d56a4620958c8e58a768c70d>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ConfigurationManager.ConfigurationManager.SettingsWindow (System.Int32 id) (at <1ee2b014d8854595b396c981966ef778>:0)
UnityEngine.GUILayout+LayoutedWindow.DoWindow (System.Int32 windowID) (at <58f888e0d56a4620958c8e58a768c70d>:0)
UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI+WindowFunction func, System.Int32 id, System.Int32 instanceID, UnityEngine.GUISkin _skin, System.Int32 forceRect, System.Single width, System.Single height, UnityEngine.GUIStyle style) (at <58f888e0d56a4620958c8e58a768c70d>:0)

[Error  : Unity Log] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced.

**Comment by ManlyMarco** [comment]
Sounds like it's a bug in that specific mod then, maybe it's using a custom UI drawer and that messes things up. I suggest reporting this to the mod author so it can hopefully be fixed.

**Comment by GingerBeardMan7** [comment]
Its an issue created when you start deleting config files that the config manager uses to manages the config of mods.

**Comment by Aromack** [comment]
I am also having a issue.  
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ConfigurationManager.SettingSearcher.CollectSettings (System.Collections.Generic.IEnumerable`1[ConfigurationManager.SettingEntryBase]& results, System.Collections.Generic.List`1[System.String]& modsWithoutSettings, System.Boolean showDebug) (at <7fcc1f060b7f4fe5bd2220dd0c943033>:0)
ConfigurationManager.ConfigurationManager.BuildSettingList () (at <7fcc1f060b7f4fe5bd2220dd0c943033>:0)
ConfigurationManager.ConfigurationManager.set_DisplayingWindow (System.Boolean value) (at <7fcc1f060b7f4fe5bd2220dd0c943033>:0)
ConfigurationManager.ConfigurationManager.Update () (at <7fcc1f060b7f4fe5bd2220dd0c943033>:0)

I uninstalled BepinEx and the configuration manager.  Started Valheim without them. Then exited the game reinstalled BepinEx and then configuration manager and still blank :(. I went thought all mods and disabled one by one and can not find the one that could be causing the conflict.

**Comment by ManlyMarco** [comment]
@Aromack Ask for help on the Valheim discord server, it seems to be a common issue they deal with.

**Comment by Aromack** [comment]
> @Aromack Ask for help on the Valheim discord server, it seems to be a common issue they deal with.

I fixed it.  Basically had to uninstall Valheim, bepinEx  and vortex.  Remove all the remnant folders.  Then reinstall and reinstall all my mods. After that it all worked.
