### ISSUE TITLE
Valheim QuickStack mod config not added to the manager

### ISSUE THREAD

**Issue by dizzyMongoose** [BepInEx/BepInEx.ConfigurationManager#26]
BepInEx version: 5.4.9
QuickStack version: 0.6.5

[Nexus Mods link](https://www.nexusmods.com/valheim/mods/29)

Installing the QuickStack mod for Valheim linked above doesn't result in the mod showing up in the configuration manager despite it having configurable values. I've attached the .cfg file from my Valheim\BepInEx\config folder.

[QuickStack.cfg.txt](https://github.com/BepInEx/BepInEx.ConfigurationManager/files/6237645/QuickStack.cfg.txt)

**Comment by ManlyMarco** [comment]
Post the log from the game (log button in config manager).

**Comment by dizzyMongoose** [comment]
Log:
[Player.log](https://github.com/BepInEx/BepInEx.ConfigurationManager/files/6246966/Player.log)

**Comment by ManlyMarco** [comment]
Nothing obvious in the log, are you sure the plugin's settings are made to work with config manager?

**Comment by dizzyMongoose** [comment]
I'm not sure the plugin is made to work with the manager, no. I was thinking based on the readme that the manager would automatically handle BepInEx plugins.

I'll attach the DLL I have for the mod: [QuickStack-29-0-6-5-1616539495.zip](https://github.com/BepInEx/BepInEx.ConfigurationManager/files/6247032/QuickStack-29-0-6-5-1616539495.zip)

**Comment by ManlyMarco** [comment]
This plugin is creating a custom config that is not seen by config manager. Report this issue to the mod author and tell them to use the default Config.

**Comment by ManlyMarco** [comment]
This plugin is creating a custom config that is not seen by config manager. This is an issue with the plugin, not with config manager. Report this issue to the mod authors and tell them to use the default Config provided by BepInEx.
