### ISSUE TITLE
Bepinex Configuration Manager no Plugins shown

### ISSUE THREAD

**Issue by Urmel108** [BepInEx/BepInEx.ConfigurationManager#29]
Hi, 
I haven't found a forum so I write here: 
I use BepInEx 5.4.10.0 on Valheim classic. 
I have 26 Plugins loaded, but if I press F1 no Plugin is shown. Plugins seem to work fine.
![bepinex](https://user-images.githubusercontent.com/83250988/116157247-ef2b0a00-a6ec-11eb-8b62-3bd7d6d8fe3e.PNG)

Earlier it worked, but since I installed some Plugin, it's broken. 
I'm not sure, but I think the latest plugin I tried to install was PreciseRotation. 
Addons are installed via Vortex. 
Configuration Manger v16.3 is installed. 
If you need any information, please contact me. 
Many thanks, 
Urmel

**Comment by bwoebi** [comment]
This is already fixed in version 16.3 which you can download here: https://github.com/BepInEx/BepInEx.ConfigurationManager/releases

**Comment by ghorsington** [comment]
Closing as it indeed has been fixed
