### ISSUE TITLE
BepInEx4 reference breaks Assembly.GetTypes() (System.Reflection)

### ISSUE THREAD

**Issue by Vheos777** [BepInEx/BepInEx.ConfigurationManager#30]
Phew, it took me over an hour to get to the bottom of this confusing exception... I hope I got it right!

Because the types [`LegacySettingSearcher`](https://github.com/BepInEx/BepInEx.ConfigurationManager/blob/d402bde665794e1685ec9aaa86abc7d70da36f7e/ConfigurationManager/Obsolete/LegacySettingSearcher.cs) and [`SavedKeyboardShortcut`](https://github.com/BepInEx/BepInEx.ConfigurationManager/blob/master/ConfigurationManager/Obsolete/Interface/SavedKeyboardShortcut.cs) (both in the _Obsolete_ folder) still exist in the code, [`GetTypes()`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.gettypes?view=net-5.0) throws [`ReflectionTypeLoadException`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.reflectiontypeloadexception?view=net-5.0) unless the user is consciously using [`BepIn4Patcher`](https://github.com/BepInEx/BepInEx.BepInEx4Upgrader) - which isn't shipped with ConfigurationManager (nor with BepInEx 5) and there's no information of such (very conditional, but actual) dependency.

And yes, there are game libraries which actually use `GetTypes()` in production code - I've stumbled upon this issue in whichever version of [AwesomeTechnology's VegetationStudio](https://assetstore.unity.com/packages/tools/terrain/vegetation-studio-103389) the game [Outward](https://store.steampowered.com/app/794260/Outward/) is using.

Obviously, the root of the issue is not the ConfigurationManager, but other libraries using `GetTypes()` **AND** using it outside of the `try-catch` block. Currently, Outward players have to harmony-patch `GetTypes()` so it ignores missing assemblies (which requires a separate plugin) and even though the patch is conveniently included in the most popular Outward modding tool ([SideLoader](https://github.com/sinai-dev/Outward-SideLoader)), it's still somewhat of a dirty, too-far-down-the-road workaround.

Removing ConfigurationManager's obsolete code and the [BepIn4Patcher reference](https://github.com/BepInEx/BepInEx.ConfigurationManager/blob/d402bde665794e1685ec9aaa86abc7d70da36f7e/ConfigurationManager/ConfigurationManager.csproj#L39) won't fix the issue at its source, but it will be at least one step up.

And if that's too risky for BepInEx4 backwards compatibility, there should at least be information that ConfigurationManager _requires_ the [`BepIn4Patcher`](https://github.com/BepInEx/BepInEx.BepInEx4Upgrader) in _some_ games (as the users won't know whether their game uses `GetTypes()` or not).

PS. I'm a huge fan of ConfigurationManager, thank you for your work <3

**Comment by Vheos777** [comment]
Ohhh I've actually missed `using BepInEx4` in my search... So it's not just the `LegacySettingSearcher`, but also [`SavedKeyboardShortcut`](https://github.com/Vheos777/BepInEx.ConfigurationManager/blob/master/ConfigurationManager/Obsolete/Interface/SavedKeyboardShortcut.cs) (also in the `Obsolete` directory)

**Comment by Vheos777** [comment]
Ok, I've finally got to forking and building and I can confirm the issue/solution - without any references to BepInEx4, GetTypes() doesn't throw exceptions. There is [one line of code](https://github.com/BepInEx/BepInEx.ConfigurationManager/blob/9f14817690e5b9d6ef94958dbb0ccd3bbd02adcf/ConfigurationManager/SettingSearcher.cs#L53) in the `CollectSettings` method referencing the obsolete classes.

**Comment by ManlyMarco** [comment]
The obsolete API is due to be removed sometime soon but this issue will likely happen with other plugins as well, like runtime editor. It sounds like the game is doing GetTypes on all assemblies, which will throw if any type is not able to be loaded. Ideally you would patch the game code that does this and make it gather types properly (e.g. https://github.com/ManlyMarco/RuntimeUnityEditor/blob/029227feb35f2543944630dd51d662e9b40f6051/RuntimeUnityEditor/Utils/Extensions.cs#L113-L118) so it's not an issue in the future.

**Comment by ManlyMarco** [comment]
There's a new utility plugin that solves this issue https://github.com/BepInEx/BepInEx.Utility#suppressgettypeserrorspatcher
