### ISSUE TITLE
BepLinEx reads version wrong.

### ISSUE THREAD

**Issue by Manwithnoplan** [BepInEx/BepInEx.ConfigurationManager#37]
BepLinEx reads 16.4 as 16.3 and skips it in deploy, have confirmed that both are at their newest versions.

**Comment by ManlyMarco** [comment]
Sounds like an issue on your end, the latest release is v16.4.

**Comment by jtbg** [comment]
@Manwithnoplan can you confirm that you have actually killed and restarted the BepInEx processes? eg:

- fully exit all Valheim instances 
- spin down any containers
- start them up fresh

Replacing the `.dll` file while the process is running isn't guaranteed to work in all environments.

**Comment by ManlyMarco** [comment]
Closing stale issue
