### ISSUE TITLE
Crashing on Startup [Timberborn]

### ISSUE THREAD

**Issue by hawkfalcon** [BepInEx/BepInEx.ConfigurationManager#38]
I was hoping to use this mod in Timberborn, but it's crashing on startup with:

[Error  : Unity Log] InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
Stack trace:
UnityEngine.Input.GetKeyDown (UnityEngine.KeyCode key) (at <cc3a14e0631b4e4eb0483c34615e9784>:0)
BepInEx.Configuration.KeyboardShortcut.IsDown () (at <73d37a760d5a4444be8d7989b489dc1a>:0)
ConfigurationManager.ConfigurationManager.Update () (at D:/SVN/BepInEx.ConfigurationManager/ConfigurationManager/ConfigurationManager.cs:644)

Any ideas on how to fix it?

**Comment by ManlyMarco** [comment]
It is as it says, a build that uses the new input system is needed in this case.

**Comment by hawkfalcon** [comment]
Got it - thanks
