### ISSUE TITLE
How can I make this plugin display in other languages or How can I use xunity.autoTranslate  translate this plugin

### ISSUE THREAD

**Issue by jarbean** [BepInEx/BepInEx.ConfigurationManager#39]
How can I make this plugin display in other languages or How can I use xunity.autoTranslate  translate this plugin

**Comment by ManlyMarco** [comment]
You can use the IMGUI translation function of XUAT to translate this plugin, check its readme for details. If you need help and it's not in the readme, feel free to ask on the BepInEx discord server since the author of XUAT is on there.

**Comment by jarbean** [comment]
thanks
