### ISSUE TITLE
[Peglin Demo] ConfigurationManager seemingly conflicts with Febucci text animator

### ISSUE THREAD

**Issue by bo0tzz** [BepInEx/BepInEx.ConfigurationManager#40]
When trying to load this plugin into the [peglin demo](pegl.in), it seems like it conflicts with the Febucci text animator library which is used in this game. That results in Febucci breaking, which is visible in the log file (https://gist.github.com/bo0tzz/f921ee3872f3c74d1e593f4263cf2119), and it also seems to break this config manager plugin - the hotkey to open the menu does nothing, even after changing it.

**Comment by ManlyMarco** [comment]
Try using this https://github.com/BepInEx/BepInEx.Utility#suppressgettypeserrorspatcher

**Comment by bo0tzz** [comment]
That fixes Febucci and removes the stacktrace from the log, replacing it with a bunch of `Could not load file or assembly 'BepInEx.BepIn4Patcher`. Unfortunately, the config manager still won't open :( Full log at https://gist.github.com/bo0tzz/27f7c44711d6afcfaf33f65ea3f3c3a9 again, although I don't think it holds anything interesting.

**Comment by ManlyMarco** [comment]
Solved in last release.
