### ISSUE TITLE
width of text box in mod config menu is zero

### ISSUE THREAD

**Issue by Fengzi2333** [BepInEx/BepInEx.ConfigurationManager#41]
![U{U23X~OY~3PX(3OPECY4P9](https://user-images.githubusercontent.com/27489008/148367555-e304c81c-a6fc-4240-87fe-4a6ee3b7e1ed.png)
can‘t input text for width of text box in mod config menu is zero

**Comment by ManlyMarco** [comment]
Can you send the game log? Click the Log button at top right and upload the file (check it for any sensitive information first).

**Comment by Fengzi2333** [comment]
here it is [output_log.txt](https://www.dropbox.com/s/9qvm53991j6vfqr/output_log.txt?dl=0)

**Comment by ManlyMarco** [comment]
Nothing wrong in the log. Can you test this build?  [ConfigurationManager.zip](https://github.com/BepInEx/BepInEx.ConfigurationManager/files/7896675/ConfigurationManager.zip)

**Comment by ManlyMarco** [comment]
Closing as stale, prease reopen this issue if it's not fixed in latest release.
