### ISSUE TITLE
Thunderstore Mod Manager?

### ISSUE THREAD

**Issue by thisischrys** [BepInEx/BepInEx.ConfigurationManager#43]
Forgive me if this was mentioned somewhere, I haven't found it.

Is there any reason this isn't on the Thunderstore Mod Manager?

I just learned about this through the info page of DSP Drone Clearing and I love it. It's the first time I'm finding a mod that's not on Thunderstore so... discoverability maybe?

**Comment by ManlyMarco** [comment]
That's a question for that particular modding community. All 1st party BepInEx plugins are meant to work in as many games as possible so we're not going to hunt each website to upload to.
