### ISSUE TITLE
 MissingMethodException: void UnityEngine.GUIStyle.set_normal(UnityEngine.GUIStyleState)

### ISSUE THREAD

**Issue by jimowushuang** [BepInEx/BepInEx.ConfigurationManager#47]
MissingMethodException: void UnityEngine.GUIStyle.set_normal(UnityEngine.GUIStyleState)

**Comment by ManlyMarco** [comment]
We're going to need more information than this. Can you post the full game log if it gets generated? If not, what game is this happening in?

**Comment by jimowushuang** [comment]
> We're going to need more information than this. Can you post the full game log if it gets generated? If not, what game is this happening in?

where i can find the log

**Comment by ManlyMarco** [comment]
It depends on the unity version, look for output_log.txt somewhere inside the game directory or appdata. If config manager window opens then there's a log button you can press to open the log.
