### ISSUE TITLE
can i hide one setting based on another

### ISSUE THREAD

**Issue by jimowushuang** [BepInEx/BepInEx.ConfigurationManager#48]
example 
setting a is 0 show setting b hide setting c and a is 1 hide b to show c

**Comment by ManlyMarco** [comment]
You need to tell it to rebuild the settings list https://github.com/BepInEx/BepInEx.ConfigurationManager/blob/master/ConfigurationManager/ConfigurationManager.cs#L157-L160

**Comment by jimowushuang** [comment]
thanks
