### ISSUE TITLE
.NET Framework v3.5 is not compatible with NETStandard 2.1

### ISSUE THREAD

**Issue by MeGaGiGaGon** [BepInEx/BepInEx.ConfigurationManager#50]
When opening the most recent version's .zip's SLN in VSCode, nothing works until ConfigurationManager.csproj's TargetFrameworkVersion is changed from v3.5 to v4.8. I'm not sure why this fixes it for me as [the .NET Standard compatibility chart](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1) says no framework versions will be supported by 2.1. Hopefully someone more familiar with .NET/C# knows why this is, but for now this fixed it for me.

More specifically, it seems all the UnityEngine things broke, with the message that 	`<package id =" netstandard" Version="2.1.0.0" Culture="neutral" PublicKeyToken="cc7b13ffcd2ddd51"/> `was missing.

**Comment by ManlyMarco** [comment]
You have to use .net 3.5 dlls for references, the project should pull them automatically from nuget. Unity itself doesn't really care after it's been built and it should work on any version of the runtime.
