### ISSUE TITLE
ConfigurationManager doesn't open after launching the game and pressing F1

### ISSUE THREAD

**Issue by GalGreenfield** [BepInEx/BepInEx.ConfigurationManager#51]
I downloaded the latest release at the time of writing this, and placed ConfigurationManager (alongisde the provided XML - I don't know where to put it) in `BepInEx/plugins`, ran the game and pressed F1, per the [How to Use section](https://github.com/BepInEx/BepInEx.ConfigurationManager#how-to-use).
It doesn't open for me.
I do want to mention that I have the BepInEx console enabled, so it opens when I start the game - I don't know if that's relevant or not.

**Comment by AzumattDev** [comment]
You would need to tell them which game this happens on.

**Comment by ManlyMarco** [comment]
Send the game log or if disabled the the bepinex log.

**Comment by bnn1** [comment]
@GalGreenfield I was having the same issue with Valheim (r2modman mod manager). I had warning in logs, something about config manager might not work with current version of bepinex. After updating bepinex the configurator started working.

**Comment by ManlyMarco** [comment]
Closing as stale, most likely old bepinex version like bnn1 said.
