### ISSUE TITLE
Custom ConfigFile cannot be shown

### ISSUE THREAD

**Issue by z-henry** [BepInEx/BepInEx.ConfigurationManager#53]
I create a new plugin base on BaseUnityPlugin and bind a new BepInEx.Configuration.ConfigFile which is under the floder "BepInEx\config\XXX". It seems like bind method works well, but F1 could not show any info about this plugin
`          
if (hsUnitID.Length <= 0)
  ConfigBind(base.Config);
else
  ConfigBind(new BepInEx.Configuration.ConfigFile(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "BepInEx/config", hsUnitID, PluginInfo.PLUGIN_GUID + ".cfg"), false, new BepInPlugin(PluginInfo.PLUGIN_GUID, PluginInfo.PLUGIN_NAME, PluginInfo.PLUGIN_VERSION)));
`

**Comment by Windows10CE** [comment]
You have to set BaseUnityPlugin.ConfigFile, that's what ConfigurationManager reads from

**Comment by z-henry** [comment]
It seems that BaseUnityPlugin.ConfigFile only provide a getter. Thanks for your answer.

**Comment by ManlyMarco** [comment]
Yep, if you want to have the settings show up in config manager you will have to use the default ConfigFile provided by BaseUnityPlugin. It's not planned to change this, at least not until BepInEx 6.
