### ISSUE TITLE
I may be missing it

### ISSUE THREAD

**Issue by N4kedGamer** [BepInEx/BepInEx.ConfigurationManager#55]
dll goes in the BepnEx/plugins folder. It isn't working. here is my log file as well
[LogOutput.log](https://github.com/BepInEx/BepInEx.ConfigurationManager/files/10098845/LogOutput.log)

**Comment by N4kedGamer** [comment]
Also this is for the game Valheim if that means anything.

**Comment by ManlyMarco** [comment]
`[Warning:   BepInEx] Plugin [Configuration Manager 17.1] targets a wrong version of BepInEx (5.4.20.0) and might not work until you update`
Update BepInEx.
