### ISSUE TITLE
Closing ConfigurationManager

### ISSUE THREAD

**Issue by heykiditsaaron** [BepInEx/BepInEx.ConfigurationManager#59]
I love this configuration manager, the only thing I could ask for is if it were possible to close the manager out by either pressing escape key or pressing F1 again, instead of having to click outside of the menu. Thank you.

**Comment by azegoca** [comment]
Or a close "X" or button. I thing F1 again is supposed to close it, but it doesn't work currently. Personally I prefer a button of some type to close the dialog window.
