### ISSUE TITLE
Configurations doesn't save on servers with -crossplay startup parameters

### ISSUE THREAD

**Issue by ViRoooz** [BepInEx/BepInEx.ConfigurationManager#60]
Hello!

I don't know is that possible, but noticed that some days ago. When I run my servers with `-crossplay` switch, then Configuration Manager doesnt save locked files (admin locked). It's probably just because mod doesnt recognize the admin correctly (with -crossplay enabled, id of player is steam_76561197960287930 instead of only numbers at server without crossplay enabled).

**Comment by Windows10CE** [comment]
This mod has no special logic for Valheim (or any game), it has no concept of admins, servers, or players.

**Comment by ManlyMarco** [comment]
Yeah, this is completely out of the scope and needs to be handled by a helper plugin for the game or by other means.
