### ISSUE TITLE
Cannot open with F1

### ISSUE THREAD

**Issue by Foul-Tarnished** [BepInEx/BepInEx.ConfigurationManager#61]
Hey, I'm trying to use this in Timberborn game with BepInExPack_Timberborn (that is based on 5.4.19) so I have to use version 17.0 of CM, as 17.1 require 5.4.20.

I'm just trying to use this with [BepInEx.GraphicsSettings](https://github.com/BepInEx/BepInEx.GraphicsSettings) to be able to disable MSAA at ultra preset, so I can interact with the Depth Pass in ReShade.
Nothing in the command prompt window, except that those 2 plugins are loaded.
I also tried to uninstall ReShade to check if there was some sort of conflict, but no changes.

F1 does nothing

```
[Message:   BepInEx] BepInEx 5.4.19.0 - Timberborn (05.02.2023 18:28:41)
[Info   :   BepInEx] Running under Unity v2022.1.24.7380445
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.19.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Configuration Manager 17.0]
[Info   :   BepInEx] Loading [Graphics Settings 1.2.1]
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Starting game version 0.3.5.1-fb48f47-gw
[Info   : Unity Log] System info:
System: Windows 11  (10.0.22000) 64bit
CPU: AMD Ryzen 7 3700X 8-Core Processor
GPU: NVIDIA GeForce GTX 1060 6GB
GPU memory: 6043MB
RAM: 16307MB
Drives:
  C:\ 93.16GB free from 464.48GB
  D:\ 8.46GB free from 71.85GB
  E:\ 50.55GB free from 931.50GB
  G:\ 166.75GB free from 859.66GB

[Info   : Unity Log] Modded: true, BepInEx
[Info   : Unity Log] Loading saved game Castorama - 2023-02-06 19h51m, Day 3-14.autosave at 2023-02-06 22:38:26Z
[Info   : Unity Log] Load time: 26535 ms
```

**Comment by Foul-Tarnished** [comment]
So I installed BepInEx 5.4.21 instead of using the one from Timberborn Thunderstore page, and use CM 17.1, and it still doesn't work.

Log is same (except versions)

I have a CH_fr QWERTZ keyboard, tried F1, CTRL+F1, ...

**Comment by ManlyMarco** [comment]
If there's a modding community for that game it's best to ask there since they most likely have a solution already. I can only guess, maybe IMGUI layer is not visible in that game, or maybe something crashes but it's not being logged.

**Comment by ManlyMarco** [comment]
Closing because of insufficient info.
