### ISSUE TITLE
TypeLoadException without stack trace

### ISSUE THREAD

**Issue by devdave** [BepInEx/BepInEx.ConfigurationManager#62]
```c#
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000070 (from typeref, class/assembly BepInEx.UnityInput, BepInEx, Version=5.4.20.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
```

I am running the JTV package & a few others so I am having trouble tracking down which mod is conflicting with ConfigManager.    

Is it possible that ` ConfigurationManager.Logger.LogError(ex);` isn't printing the stack trace when the exception is caught?

**Comment by devdave** [comment]
I ran the disk/player.log at `ALL` level and didn't see anything in particular that might be causing the exception.

**Comment by ManlyMarco** [comment]
Update BepInEx.

**Comment by ManlyMarco** [comment]
Closing stale issue.
