### ISSUE TITLE
[Question / Not a bug]

### ISSUE THREAD

**Issue by JoewAlabel** [BepInEx/BepInEx.ConfigurationManager#64]
Just one simple question, please.
I prefer create the Config file at my own mod folder inside Plugins folder's, instead BepinEx default Config folder.
And I use this command to set my ConfigFile:
`public static ConfigFile configFile = new ConfigFile(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), MyPluginInfo.PLUGIN_NAME, "Config.cfg"), true);`

How could I make ConfiguratorManager compatible, please?
And is there a way I can change F1 key and embeed PluginConfigurator in my dll mod file, please?

Thanks!!!

**Comment by ManlyMarco** [comment]
ConfigurationManager only supports config files attached to plugin instances.
On a side note, placing config files inside the plugins folder is heavily discouraged.
