### ISSUE TITLE
Keyboard shorcuts do not work

### ISSUE THREAD

**Issue by JoewAlabel** [BepInEx/BepInEx.ConfigurationManager#65]
I am getting the error:

`[Error  : Unity Log] InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.`

The code:
```
if (MyHotKey.Value.IsDown())
{
	// action here...
 }
```
Is not working...

I can not use shortcurts cause an Unity's Player Settings problem. :P

I can manually set the keys with this code:
```
if (Keyboard.current[Key.LeftAlt].isPressed)
{
    if (Keyboard.current[Key.Digit4].wasPressedThisFrame)
    {
        //Log.LogInfo("Keys Pressed!");
    }
}
```
But I CAN NOT find a way to allow players set your own keys =(

Can anyone tell me how I make it work with the `KeyboardShortcut(KeyCode.Keypad1, KeyCode.LeftAlt));` , please?

Thank you!

**Comment by ManlyMarco** [comment]
Update BepInEx.

**Comment by JoewAlabel** [comment]
> 

It is not woreking with BepInEx6 (BepInEx Bleeding Edge (BE) builds). I am using latest build.
But it works with BepInEx5 latest build =(

**Comment by ManlyMarco** [comment]
Use BepInEx5 latest, v6 is not supported at the moment.

**Comment by JoewAlabel** [comment]
> Use BepInEx5 latest, v6 is not supported at the moment.

Ok. thank you!!!!!
