### ISSUE TITLE
Licensing clarification. Must plugins linking with configuration manager be GPL 3?

### ISSUE THREAD

**Issue by UANITY** [BepInEx/BepInEx.ConfigurationManager#7]
Sorry if this isn't the right place to ask this question.
I see BepinEx uses a MIT license and the Configuration Manager uses a GPL 3 license. Must plugins linking with the configuation manager use a GPL 3 or can I use a different license?

**Comment by denikson** [comment]
Greetings!

The GPL license for Configuration Manager was a leftover from times when one didn't have to reference Configuration Manager directly and it did all of the work automatically.

Overtime the architecture changed, yet GPL was left. It is indeed not reasonable to have this project be GPL anymore, as it restricts everyone trying to reference it.

I've changed the license to LGPL which allows to license projects referencing Configuration Manager using a different license.  
If you find any other similar plugins in BepInEx org (i.e. one has to add a reference to them) yet they are GPL, feel free to ask about changing the license to LGPL. From a quick glance I didn't see any other plugins we have that have the same issue.
