### ISSUE TITLE
Need compatibility for BepInEx v6

### ISSUE THREAD

**Issue by abevol** [BepInEx/BepInEx.ConfigurationManager#71]
Thanks for your work.

**Comment by ManlyMarco** [comment]
Yes, I'm mostly waiting for v6 to get to a solid RC state or otherwise close to release. You can use https://github.com/sinai-dev/BepInExConfigManager in the meantime.

**Comment by L4urr** [comment]
> Yes, I'm mostly waiting for v6 to get to a solid RC state or otherwise close to release. You can use https://github.com/sinai-dev/BepInExConfigManager in the meantime.

This one its for BepInEx 6 - IL2CPP or BepInEx 5 - Mono. 
But if the game its Mono and it only works with BepInEx 6, then the ConfigurationManager its not working, because for Mono it needs BepInEx 5.
Game Example: Dinkum
I didn't found any Configuration Manager to work for this game.
