### ISSUE TITLE
Where is the .dll

### ISSUE THREAD

**Issue by Warparty92** [BepInEx/BepInEx.ConfigurationManager#73]
I took a look through the files and there is no .dll file to put into the plugins folder.
[BepInEx.ConfigurationManager-master.zip](https://github.com/BepInEx/BepInEx.ConfigurationManager/files/12232861/BepInEx.ConfigurationManager-master.zip)

**Comment by ManlyMarco** [comment]
Don't download the source code.
https://github.com/BepInEx/BepInEx.ConfigurationManager/releases

**Comment by Warparty92** [comment]
thanks
