### ISSUE TITLE
run_bepinex.sh script errors on Kubuntu 23.04

### ISSUE THREAD

**Issue by GhostCoder22** [BepInEx/BepInEx.ConfigurationManager#74]
After downloading **BepInEx_unix_5.4.22.0.zip** and extracting it's contents to **.steam/debian-installation/steamapps/common/Angel Legion** (which is **Angel Legion - Idle RPG**'s root folder), I continued following BepInEx's installation guide by adding **AngelLegion.exe** to **run_bepinex.sh**'s **executable_name** script line as per the installation directions, and I did all this before executing **chmod u+x run_bepinex.sh** within Konsole. My next step was adding **./run_bepinex.sh %command%** to the games launch options within Steam itself before running the game, but every time I try to run the game, the Steam client fails run the game with BepInEx and I found out why.

Apparently, running **./run_bepinex.sh** was a bust since Konsole complains **_bash: ./run_bepinex.sh: cannot execute: required file not found_**, so I tried running the command **bash run_bepinex.sh** instead and got a whole slew of errors when attempting to run the script:
**run_bepinex.sh: line 8: $'\r': command not found
run_bepinex.sh: line 11: $'\r': command not found
run_bepinex.sh: line 16: $'\r': command not found
run_bepinex.sh: line 18: $'\r': command not found
run_bepinex.sh: line 21: $'\r': command not found
run_bepinex.sh: line 24: $'\r': command not found
run_bepinex.sh: line 28: $'\r': command not found
run_bepinex.sh: line 31: $'\r': command not found
run_bepinex.sh: line 50: syntax error near unexpected token `$'in\r''
'un_bepinex.sh: line 50: `case $os_type in**

I was able to fix lines 8 through 31 by just adding **#** to **run_bepinex.sh**, but line **50** I have absolutely no idea how to fix since I'm new to using Bash scripts. Please help?

Please note that **uname -s** reports **Linux**.

**Comment by ManlyMarco** [comment]
This is a [BepInEx](https://github.com/BepInEx/BepInEx) issue, not ConfigurationManager. See https://docs.bepinex.dev/articles/advanced/steam_interop.html and ask on the BepInEx discord server if you can't get it to work.
