### ISSUE TITLE
ConfigEntry<Color> suggestion

### ISSUE THREAD

**Issue by RTMecha** [BepInEx/BepInEx.ConfigurationManager#76]
The ConfigEntry<Color> configs only use sliders. It would be nice if there was an inputfield for editing the color's hex code.

**Comment by ManlyMarco** [comment]
Any ideas on how to do the UI to allow both sliders and hex value edits?

**Comment by RTMecha** [comment]
![image](https://github.com/BepInEx/BepInEx.ConfigurationManager/assets/125487712/57277355-d6c9-4b14-abf9-96ecdb73ddb9)

Pretty much what I'm thinking

**Comment by redseiko** [comment]
Uh I'll give it a shot, it might take awhile since my scope was limited to Valheim modding.

Are there any guidelines/styling/etc to read and follow for PRs?
