### ISSUE TITLE
F12 don't show BepIn window

### ISSUE THREAD

**Issue by d4b005t** [BepInEx/BepInEx.ConfigurationManager#77]
Hi all,
I'm trying to learn game modding. Following the installation procedure of BepInEx i run the game, and i try to open the window with F12 key. But seems that the game uses that key for screenshot purpose, and it doesn't appear the window. I can't reconfigure F12 command behaviour from the game's key settings menu.
BepInEx correctly initialize the folder, but from log seems i never press the F12 key.

`[Message:   BepInEx] BepInEx 5.4.22.0 - DawnOfMan (12/10/2023 02:47:02)
[Info   :   BepInEx] Running under Unity v2022.3.8.11922172
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
`
So i try to change F12 key with another unused key.
[Here](https://hub.sp-tarkov.com/forum/thread/3171-modded-no-f12-on-3-5-6/) someone says to change com.bepis.bepinex.configurationmanager.cfg inside my \BepInEx\config folder, but i find only BepInEx.cfg file inside that folder, and there isn't a configuration for the menu show key inside.

**Comment by ManlyMarco** [comment]
You've put the plugin into a wrong folder since BepInEx doesn't load it. The default hotkey is F1.

**Comment by d4b005t** [comment]
Hi ManlyMarco, thanks for answer my question. I think your work is great!
I'm trying to mod DawnOfMan game, following [this](https://github.com/ManlyMarco/RuntimeUnityEditor) procedure (section "How to use BepInEx"), i placed the files in the main root directory of the game, and the result is this folder:
![image](https://github.com/BepInEx/BepInEx.ConfigurationManager/assets/10092679/aef2a8ba-e608-4bee-9592-6cc1fdb55c51)
I try to reinstall the whole game for have a clean installation folder. Unluckly, F1 and F12 gives the same result: the window doesn't appear. The log output the same result.

**Comment by ManlyMarco** [comment]
This much looks fine, you probably just put config manager into a wrong directory, it should be inside bepinex/plugins.

**Comment by d4b005t** [comment]
Hi and thanks another time...
The BepInEx folder has this tree:

`
cache
      chainloader_typeloader.dat
      harmony_interop_cache.dat
config\
      BepInEx.cfg
core\
      0Harmony.dll
      0Harmony.xml
      0Harmony20.dll
      BepInEx.dll
      BepInEx.Harmony.dll
      BepInEx.Harmony.xml
      BepInEx.Preloader.dll
      BepInEx.Preloader.xml
      BepInEx.xml
      HarmonyXInterop.dll
      Mono.Cecil.dll
      Mono.Cecil.Mdb.dll
      Mono.Cecil.Pdb.dll
      Mono.Cecil.Rocks.dll
      MonoMod.RuntimeDetour.dll
      MonoMod.RuntimeDetour.xml
      MonoMod.Utils.dll
      MonoMod.Utils.xml
patchers\
plugins\
LogOutput.log`

"plugin" folder is empty.

**Comment by ManlyMarco** [comment]
Uhh, what? Those aren't even instructions for this plugin, they are for runtime editor, and you clearly didn't follow them since runtime editor files are missing from the directory list you posted. All you did so far was install BepInEx.

**Comment by d4b005t** [comment]
Hi ManlyMarco, thanks again.
Yes, what you said is true... I miss step 2... Now all works as expected...
Sorry for the disturb!
