### ISSUE TITLE
Using version 18.1, some translated texts are not displayed

### ISSUE THREAD

**Issue by XHxiaohuaXH** [BepInEx/BepInEx.ConfigurationManager#81]
![QQ图片20240125002529](https://github.com/BepInEx/BepInEx.ConfigurationManager/assets/134010022/9b23796f-1d36-46e6-9338-fee03d2f10f4)

Version 18.0 used in the above figure

![QQ图片20240125002417](https://github.com/BepInEx/BepInEx.ConfigurationManager/assets/134010022/de51ece1-6870-47ad-afb2-36d13355f16f)

Version 18.1 used in the above figure

————————————————————————
The game using the IL2CPP framework uses the IL2CPP version, and all translations are not displayed

![QQ图片20240125003236](https://github.com/BepInEx/BepInEx.ConfigurationManager/assets/134010022/9300f75f-f893-407a-9b66-bda28a01c5a3)
The game in the above picture is based on the IL2CPP framework and uses the IL2CPP version. Even with the translation used, the translated text will not be displayed

**Comment by ManlyMarco** [comment]
IMGUI translations need to be enabled in AutoTranslatorConfig.ini

**Comment by XHxiaohuaXH** [comment]
IMGUI has been enabled, but version 18.1 still does not display partial translations，Just like in the picture.

**Comment by ManlyMarco** [comment]
Closing this issue since this is not an issue with ConfigurationManager as it never supported localization in the first place. At best it's an AutoTranslator issue.
