### ISSUE TITLE
Unable to bring up menu by pressing F1

### ISSUE THREAD

**Issue by ohuo133233** [BepInEx/BepInEx.ConfigurationManager#85]
![image](https://github.com/BepInEx/BepInEx.ConfigurationManager/assets/41932817/2e5cdc86-e250-4328-b4a3-5e2a19adea39)

[Message:   BepInEx] BepInEx 5.4.22.0 - Lethal Company (2024/3/2 18:23:37)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Configuration Manager 18.2.1]
[Message:   BepInEx] Chainloader startup complete

No response when using F1

**Comment by ManlyMarco** [comment]
Try using different entry point or hiding manager object in bepinex.cfg.

**Comment by ohuo133233** [comment]
> Try using different entry point or hiding manager object in bepinex.cfg.
Thank you，Can you provide a detailed operating procedure or reference url？

**Comment by ManlyMarco** [comment]
See https://docs.bepinex.dev/v5.4.21/articles/user_guide/troubleshooting.html

**Comment by ohuo133233** [comment]
> See https://docs.bepinex.dev/v5.4.21/articles/user_guide/troubleshooting.html

Thank you
