### ISSUE TITLE
Menu not working and keeps giving the same error

### ISSUE THREAD

**Issue by FilipNones** [BepInEx/BepInEx.ConfigurationManager#92]
[Message: Preloader] BepInEx 6.0.0-be.688 - NIGHT-RUNNERS PROLOGUE
[Message: Preloader] Built from commit 49015217f3becf052d33fa4658ac19229f5daa3a
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2018.4.26f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [Configuration Manager 18.3.0]
[Info   :Il2CppInterop] Registered mono type ConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviour in il2cpp domain
[Info   :   BepInEx] Loading [Unlock all cars 1.0.0]
[Info   :   BepInEx] Loading [Real car names 1.0.1]
[Message:   BepInEx] Chainloader startup complete
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.IO.FileNotFoundException: Could not load file or assembly 'UnityEngine.InputLegacyModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UnityEngine.InputLegacyModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at BepInEx.Configuration.KeyboardShortcut.IsDown()
   at ConfigurationManager.ConfigurationManager.Update() in D:\SVN\BepInEx.ConfigurationManager\ConfigurationManager.Shared\ConfigurationManager.cs:line 696
   at Trampoline_VoidThisConfigurationManager.ConfigurationManager+ConfigurationManagerBehaviourUpdate(IntPtr , Il2CppMethodInfo* )

the game doesn't have UnityEngine.InputLegacyModule.dll, why is needed?

**Comment by ManlyMarco** [comment]
For input, though it also supports new input system. If InputLegacyModule is completely stripped out then IMGUIModule is surely stripped out too, which makes this plugin not possible to use with the game (at least without somehow restoring the functionality).

**Comment by FilipNones** [comment]
I see... thanks for the explanation
