### ISSUE TITLE
cant open config manager after reassigning the keybinding

### ISSUE THREAD

**Issue by chunsanglai** [BepInEx/BepInEx.ConfigurationManager#94]
[Info   :   BepInEx] Running under Unity v2021.3.38.8007589
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 6 plugins to load
[Info   :   BepInEx] Loading [Auto Light Switch 1.1.0]
[Info   :Auto Light Switch] Plugin AutoLightSwitch by AToxicNinja is loaded!
[Info   :   BepInEx] Loading [Configuration Manager 18.3]
[Error  :   BepInEx] Failed to read keybind from settings: Requested value '-' was not found.

**Comment by ManlyMarco** [comment]
How did you reassign it?

**Comment by chunsanglai** [comment]
> How did you reassign it?

file: com.bepis.bepinex.configurationmanager.cfg 


## The shortcut used to toggle the config manager window on and off.
## The key can be overridden by a game-specific plugin if necessary, in that case this setting is ignored.
# Setting type: KeyboardShortcut
# Default value: F1
Show config manager = -

**Comment by toebeann** [comment]
Try `Minus` or `KeypadMinus`

**Comment by ManlyMarco** [comment]
Yep, you can't put in just anything in there, only what's on the list of allowed options. Change the setting with config manager to avoid this in the first place.

**Comment by chunsanglai** [comment]
> Try `Minus`, or `KeypadMinus` for the minus key on the numpad

Minus seems to work fine, thanks!
